apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: amiroous/docker-k8s-fibonacci-complex-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: ["**/*.js", "**/*.css", "**/*.html"]
    - image: amiroous/docker-k8s-fibonacci-complex-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: ["**/*.js"]
    - image: amiroous/docker-k8s-fibonacci-complex-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: ["**/*.js"]
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
      - k8s/server-cluster-ip-service.yaml
